### ISSUE TITLE
Filter for and set null values

### ISSUE THREAD

**Issue by recunius** [MorphiaOrg/morphia#2330]
Hi,

I'm wondering if I am missing an obvious workaround here.

What is the correct way to filter for null values? The value parameter for filter methods are not marked with `@Nullable` and the package is marked as `@NonNullApi` in package-info.java

How can Morphia be used with Kotlin when the the variable is defined as nullable with, for instance `Any?`?

A similar problem exists at least with the Update operations. They also do not allow for null values. So how can you set a value to null in an update?

Thanks,
Bob

** Please complete the following information: **
    Server Version: 4.2.22
    Driver Version: 4.2.3
    Morphia Version: 2.2.10

**Comment by evanchooly** [comment]
I just got back from a conference but i'm hoping to collect the last 2.3.1 issues and do a release this next week.

**Comment by Hovhannisyan-K** [comment]
will this be ready by Friday? @evanchooly

**Comment by evanchooly** [comment]
2.3.1 went out this week, btw.

**Comment by recunius** [comment]
Thank you for the quick turnaround!

**Comment by evanchooly** [comment]
No problem.  I did a quick audit and i think I've corrected all the places that should allow for null values but if I missed some please do let me know.  Annotating at the package level is a very broad brush but it's the easiest route to get things done.

**Comment by Hovhannisyan-K** [comment]
thank you so much we will check if we still missing nullable params!
