### ISSUE TITLE
Native Query call throwing NullPointer exception

### ISSUE THREAD

**Issue by AmitKuGarg** [MorphiaOrg/morphia#2566]
** I get NullPointer exception when I execute native query on: **
final BasicDBObject query = new BasicDBObject();
query.put("field1", 114494);
query.put("field2", 31200);
datastore.getDatabase().getCollection("MyCollection").find(query).iterator().next();

**datastore refers to dev.morphia.Datastore. 

**If I set DatastoreHolder.holder.set(datastore ) then problem goes away but I am not sure if this is right thing to do**

** Version information: **
    Server Version: Mongo 4.2
    Driver Version: 4.10
    Morphia Version: morphia-core 2.4.1 & mongodb-driver-sync 4.10.2

**Comment by evanchooly** [comment]
This is fixed in 2.4.4.

**Comment by AmitKuGarg** [comment]
Issue still persist. I am still getting NullPointerException.

![image](https://github.com/MorphiaOrg/morphia/assets/8405845/bb90aa62-308d-42f5-bc25-cb6425e398da)

**Comment by evanchooly** [comment]
hrm.  Ok I'll take a look.

**Comment by evanchooly** [comment]
ok.  a couple of notes.  You're sidestepping part Morphia by going to the `Database` directly and so certain bits aren't set up correctly.  The good news is I have that fixed in a branch that'll i'll merge and release soon.  it completely does away with that set up that your approach uses.  So what you have *here* should work with that branch.  But that doesn't help you today.

You can use a native query today with Morphia with just a few tweaks.

```java
var query = new Document();
query.put("field1", 114494);
query.put("field2", 31200);
datastore.find(User.class, query).iterator(new FindOptions().collection("MyCollection")).tryNext();
```

You can pass in the native query as a `Document` as opposed to a `BasicDBObject` (which you shouldn't be using now anyway as `Document` is the preferred/modern type by the driver.)  You need to give `find()` a type along with the query document.  If you want to query in an alternative collection, you pass that to the `FindOptions` as shown here.  If you update to the code I've shown here, you should be good to go.

**Comment by evanchooly** [comment]
I just tested your scenario with that completed branch and it does work as expected.  That will be in 2.4.5.
